blank_issues_enabled: false
contact_links:
  - name: Discussions
  - url: https://github.com/Emmiwinks/waakaka/discussions
    about: Discuss about our software!
  - name: Christoph Wellm
    url: https://github.com/Emmiwinks/waakaka
    about: Please conduct the README for more information about contacts.
  - name: Sophie Emmrich
    url: https://github.com/Emmiwinks/waakaka
    about: Please conduct the README for more information about contacts.
